homeassistant:
  allowlist_external_dirs:
    - /media/data/recordings

  media_dirs:
    media: /media/data
    recording: /media/data/recordings

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

sensor:
  - platform: history_stats
    name: "Dzisiejszy czas TV"
    entity_id: media_player.living_room_tv
    state: "playing"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: average
    unique_id: __legacy__
    name: 'Dom - Uśredniony pobór prądu'
    duration:
      minutes: 5
    entities:
      - sensor.dom_pobor_pradu
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_use_percent
      - type: swap_use_percent
      - type: processor_temperature
      - type: processor_use

cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garaż - Brama"
        unique_id: "sensor.garage_door"
        value_template: "{{ None }}"
        open_cover:
          service: script.open_garage_door
        close_cover:
          service: script.close_garage_door
        stop_cover:
          service: script.stop_garage_door
  
template:
  - sensor:
    - name: 'Conibase balance'
      unique_id: 'sensor.coinbase_balance'
      state: '{{ ((states.sensor.coinbase_staked_ada.state | float * states.sensor.ada_exchange_rate.state | float + states.sensor.coinbase_eth_wallet.state | float * states.sensor.eth_exchange_rate.state | float)) | round(2) }}'
      unit_of_measurement: 'PLN'
    - name: 'Garaż - Temperatura'
      unique_id: 'sensor.garage_temperature'
      state: '{{ None }}'
      unit_of_measurement: '°C'
      device_class: 'temperature'
    - name: 'Garaż - Wilgotność'
      unique_id: 'sensor.garage_humidity'
      state: '{{ None }}'
      unit_of_measurement: '%'
      device_class: 'humidity'
    - name: 'Garaż - Ciśnienie'
      unique_id: 'sensor.garage_pressure'
      state: '{{ None }}'
      unit_of_measurement: 'hPa'
      device_class: 'pressure'
    - name: 'Garaż - Opór gazów VOC'
      unique_id: 'sensor.garage_gas'
      state: '{{ None }}'
      unit_of_measurement: 'Ω'
      device_class: 'gas'
  - binary_sensor:
    - name: 'Garaż - Samochód'
      unique_id: 'sensor.garage_car_presence'
      state: '{{ None }}'
      device_class: 'occupancy'
      icon: 'mdi:car'


rest_command:
  open_garage_door:
    url: "https://api.scs.iot.telekom.com/m2m/endpoints/IMEI%3A---------------/downlinkMsg/0/data"
    username: "------------------------"
    password: "----------------"
    method: put
    content_type: "application/json"
    headers:
      accept: "application/json"
    payload: '{"resourceValue":"garage-door-open"}'
  close_garage_door:
    url: "https://api.scs.iot.telekom.com/m2m/endpoints/IMEI%3A---------------/downlinkMsg/0/data"
    username: "------------------------"
    password: "----------------"
    method: put
    content_type: "application/json"
    headers:
      accept: "application/json"
    payload: '{"resourceValue":"garage-door-close"}'
  stop_garage_door:
    url: "https://api.scs.iot.telekom.com/m2m/endpoints/IMEI%3A---------------/downlinkMsg/0/data"
    username: "------------------------"
    password: "----------------"
    method: put
    content_type: "application/json"
    headers:
      accept: "application/json"
    payload: '{"resourceValue":"garage-door-click"}'

shell_command:
  record_staircase_shell: '/home/homeassistant/bin/record_staircase.sh {{ state_attr("camera.wejscie_kamera", "access_token") }}'

python_script:

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
